### ISSUE TITLE
Can I use lexr in 2021?

### ISSUE THREAD

**Issue by pedrohdev** [zsmoore/lexr#9]
This project has a last commit in 2018, I wanted to use lexr in my project, but I don't know if it's trusted for 2021

Sorry for my english 😅

**Comment by zsmoore** [comment]
Hey yes you can totally use Lexr! If there are any features you would like feel free to open issues or if things might break on you.  Most of the feature set is complete with the exception of more languages built in.  Let me know what you think!

**Comment by pedrohdev** [comment]
Hey man, i can't use lexr! I don't use transpiler anymore :(
